### ISSUE TITLE
DataParallel该怎么用

### ISSUE THREAD

**Issue by ZouJoelin** [zzz47zzz/CET#3]
1. 按照源代码来跑，报错：`AttributeError: 'DataParallel' object has no attribute 'train_model'`。定位到问题应该是运行 `mian.py` 中 `model = torch.nn.DataParallel(model, device_ids=list(range(torch.cuda.device_count()))` 后，model被封装成DataParallel类中的module。故擅自添加了 `model = model.module` 后不再报错。

2. 但是用了DataParallel貌似仍然是单卡运行（4块可用）。请问该如何解决？

3. 单卡跑的时候提示 `CUDA out of memory`，batch_size用了默认的8，单个GPU内存10G，调整为3左右才可顺利跑起来。

**Comment by zzz47zzz** [comment]
我们之前的实验中没有用到DataParallel。不过根据所提出的问题，我发现只对model.pretrain_model用DataParallel进行封装就不会报错，已经更新了代码在GitHub上。
